config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  use_doorkeeper
  root 'products#index'

  devise_for :users, controllers: { sessions: 'sessions' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  namespace :api do
    namespace :v1 do
      concern :commentable do
        resources :comments
      end

      resources :products do
        resources :likes, shallow: true, only: %i[create]
      end
      resources :order_lines
      resources :orders
      resources :users, concerns: :commentable
      resources :transactions, only: [:index]
      post '/authenticate', to: 'authentication#authenticate'
      post '/webhook', to: 'orders#webhook'
    end
  end

  concern :commentable do
    resources :comments
  end

  resources :products, concerns: :commentable do
    resources :likes, shallow: true, only: %i[create destroy]
  end
  resources :order_lines
  resources :orders, concerns: :commentable
  post 'checkout', to: 'orders#checkout'
  resources :logs, only: [:index]
  resources :transactions, only: [:index]
  get 'cart', to: 'orders#cart'

  resources :apidocs, only: [:index]
  get 'json', to: 'apidocs#json'
end

app/models/order.rb
# frozen_string_literal: true

# Class that represents the Model for the Order schema
class Order < ApplicationRecord
  before_save :set_total

  has_many :order_lines, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  enum status: { in_process: 0, recieved: 1, on_route: 2, delivered: 3 }

  private

  def set_total
    self[:total] = order_lines.sum(&:total)
  end
end

app/controllers/api/v1/orders_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # Define the Controllers required for the Order endpoints on API
    class OrdersController < ApiController
      skip_before_action :require_login!, only: %i[webhook]
      before_action :set_order, only: %i[show update]

      # Method that responds to the get request to list all the records
      # of orders from a logged user
      def index
        result = Operations::OrderOperations::ApiIndex.call(user: current_user)
        render json: { data: { order: result[:model] } }
      end

      # Method that responds to the update request to close an order from a cart
      # adds the user doing the order, the date of the order and changes its status
      # to recieved so its no longer show on the cart, and delete its from the session
      def update
        result = Operations::OrderOperations::ApiUpdate.call(params: params[:id], user: current_user)
        render json: { data: { order: result[:model] } }
      end

      def webhook
        event = nil

        begin
          sig_header = request.env['HTTP_STRIPE_SIGNATURE']
          payload = request.body.read
          event = Stripe::Webhook.construct_event(payload, sig_header, ENV['ENDPOINT_SECRET'])
        rescue JSON::ParserError
          return status 400
        rescue Stripe::SignatureVerificationError
          return status 400
        end

        Orders::WebhookService.call(event)
      end

      private

      def order_params
        params.require(:order).permit(:user_id, :date, :status)
      end

      def set_order
        @order = authorize Orders::OrderFinderService.call(params[:id])
      end
    end
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

# Define the Controllers required for the Order endpoints
class OrdersController < ApplicationController
  before_action :set_order, only: %i[show update checkout]

  # Method that responds to the get request to list all the records
  # of orders from a logged user
  def index
    result = Operations::OrderOperations::Index.call(user: current_user)
    @orders = result[:model]
  end

  # Method that responds to the get request to show an specific order
  def show; end

  # Method that responds to the /cart endpoint to show the cart that is active
  # on the current session
  def cart
    @order = current_order
    @order_lines = current_order.order_lines
  end

  # Method that responds to the update request to close an order from a cart
  # adds the user doing the order, the date of the order and changes its status
  # to recieved so its no longer show on the cart, and delete its from the session
  def update
    if Operations::OrderOperations::Update.call(order: @order, user: current_user)
      session.delete(:order_id)
      redirect_to products_path
    else
      render :cart
    end
  end

  def checkout
    @session = Orders::CheckoutService.call(current_user, @order, root_url, cart_url)

    redirect_to @session.url, allow_other_host: true
  end

  private

  def order_params
    params.require(:order).permit(:user_id, :date, :status)
  end

  def set_order
    result = Operations::OrderOperations::Show.call(params: params[:id])
    @order = authorize result[:model]
  end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

# Helpers for Order views
module OrdersHelper
end

app/views/orders/_order_card.html.erb
<div class="flex flex-col p-2 gap-2 text-lg border-2 border-slate-300 items-center">
  <div class="flex flex-col gap-2 justify-center items-center">
    <p>Order: <%= order.id %></p>
    <p>Date: <%= order.date %></p>
    <p>Total: $<%= number_with_precision(order.total, precision: 2) %></p>
    <p>Status: <%= order.status.capitalize %></p>
  </div>

  <div class="grid grid-cols-2 gap-4">
    <% order.order_lines.each do |order_line| %>
      <div class="flex flex-col p-2 gap-2 text-lg border-2 border-slate-300 items-center">
        <p class="text-2xl"><%= order_line.product.name.capitalize %></p>
        <p>Cost: $ <%= number_with_precision(order_line.product.price, precision: 2) %></p>
        <p>Subtotal: $ <%= number_with_precision(order_line.total, precision: 2) %></p>
      </div>
    <% end %>
  </div>

  <% unless current_page?(order_path(order)) %>
  <%= link_to "See more...", order_path(order), { class: button_style } %>
  <% end %>
</div>

app/views/orders/cart.html.erb
<div class="flex flex-col gap-2 p-6">
  <div class="grid grid-cols-4 gap-2 p-2 border-b-2 border-slate-500">
    <% @order_lines.each do |order_line| %>
      <div class="flex flex-col p-2 gap-2 border-2 border-slate-300 items-center">
        <p class="text-4xl"><%= order_line.product.name.capitalize %></p>
        <p class="text-2xl">Cost: $ <%= number_with_precision(order_line.product.price, precision: 2) %></p>
        <p class="text-2xl">Subtotal: $ <%= number_with_precision(order_line.total, precision: 2) %></p>

        <% if policy(order_line).update? %>
          <%= form_with model: order_line, html: {class: "flex flex-col justify-center items-center gap-6 p-4 border-2 border-slate-300"} do |form| %>
            <%= form.hidden_field :product_id, value: order_line.product.id %>
            <%= form.label :quantity %>
            <%= form.number_field :quantity, value: order_line.quantity, required: true %>
            <%= form.submit "Update", { class: button_style } %>
          <% end %>

          <%= button_to "Delete item", order_line_path(order_line), { method: :delete, class: button_style } %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="flex flex-col gap-4 text-4xl self-end">
    <div>
      <p>Total: </p>
      <p>$ <%= number_with_precision(current_order.total, precision: 2) || 0.00%></p>
    </div>
    <div>
      <% if @order.id.nil? || @order.order_lines.empty? %>
        <p>Add Products to buy</p>
      <% elsif current_user&.customer? %>
        <%= button_to "Buy now!", checkout_path, data: { turbo: false }, params: {id: @order.id} %>
      <% else %>
        <p>Sign in as customer to buy</p>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<div class="flex flex-col justify-center items-center">
  <div class="grid grid-cols-4 gap-2 p-2">
    <% @orders.each do |order| %>
      <%= render partial: "order_card", locals: { order: order } %>
    <% end %>
  </div>

  <%= link_to "Back", :back, {class: button_style} %>
</div>

app/views/orders/show.html.erb
<div class="flex flex-col gap-4 p-2 justify-center items-center">
  <%= render partial: "order_card", locals: { order: @order } %>

  <% if policy(Comment).create? %>
    <%= render partial: "comments/form", locals: { commentable: @order } %>
  <% end %>

  <%= render partial: "comments/comments", locals: { commentable: @order } %>

  <%= link_to "Back", :back, { class: button_style } %>
</div>