config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  use_doorkeeper
  root 'products#index'

  devise_for :users, controllers: { sessions: 'sessions' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  namespace :api do
    namespace :v1 do
      concern :commentable do
        resources :comments
      end

      resources :products do
        resources :likes, shallow: true, only: %i[create]
      end
      resources :order_lines
      resources :orders
      resources :users, concerns: :commentable
      resources :transactions, only: [:index]
      post '/authenticate', to: 'authentication#authenticate'
      post '/webhook', to: 'orders#webhook'
    end
  end

  concern :commentable do
    resources :comments
  end

  resources :products, concerns: :commentable do
    resources :likes, shallow: true, only: %i[create destroy]
  end
  resources :order_lines
  resources :orders, concerns: :commentable
  post 'checkout', to: 'orders#checkout'
  resources :logs, only: [:index]
  resources :transactions, only: [:index]
  get 'cart', to: 'orders#cart'

  resources :apidocs, only: [:index]
  get 'json', to: 'apidocs#json'
end

app/models/product.rb
# frozen_string_literal: true

# Class that represents the Model for the Product schema
class Product < ApplicationRecord
  # Saves which user did a change on the Product
  attr_accessor :changed_by

  before_update :new_log_update

  has_many :order_lines, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :logs, as: :loggable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_and_belongs_to_many :tags
  has_one_attached :avatar do |attachable|
    attachable.variant :variant, resize_to_limit: [220, 220]
  end

  # Method that checks which user liked the current product
  def liked_by?(current_user)
    likes.where(user_id: current_user.id).exists?
  end

  # Method that finds which user liked the current product
  def find_like(current_user)
    likes.find_by(user_id: current_user.id)
  end

  # Method that checks if the quantity passed on the order_line is
  # less than the stock of the product
  def available_stock?(quantity)
    stock >= quantity
  end

  def avatar_url
    return name unless avatar.attached?

    Rails.application.routes.url_helpers.rails_representation_url(avatar.variant(resize: '220x220'), only_path: true)
  end

  private

  def new_log_update
    return unless changed_by.admin? || changed_by.support?

    changes.each do |key, value|
      unless key == 'updated_at'
        logs.create(attr: key, old_val: value[0], new_val: value[1],
                    user_id: changed_by.id)
      end
    end
  end
end

app/controllers/api/v1/products_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # Define the Controllers required for the Product endpoints on API
    class ProductsController < ApiController
      skip_before_action :require_login!, only: %i[index]
      before_action :pundit_authorize, except: %i[index show]
      before_action :set_product, only: %i[edit update destroy]
      before_action :new_order_line, only: %i[index show]

      # Method that responds to the get request to list all the records
      # of products
      def index
        @products = Operations::ProductOperations::ApiIndex.call(params: query_params)
        @pagy, @records = pagy(@products[:model], items: 10)
        @records = ProductRepresenter.for_collection.new(@records)
        render json: { data: @records }.merge!(meta: { pagination: pagy_headers_hash(@pagy) }), status: :ok
      end

      # Method that responds to the get request to show an specific product
      def show
        result = Operations::ProductOperations::ApiShow.call(params: params[:id])
        render json: { data: { product: result[:model] } }
      end

      # Method that respond to the create request to create a new product
      def create
        result = Operations::ProductOperations::ApiCreate.call(params: product_params)
        render json: { data: { product: result[:model] } }, status: :created
      end

      # Method that responds to the update request to check if the user is an admin
      # and changes the stock and price params
      def update
        result = Operations::ProductOperations::ApiUpdate.call(
          params: permitted_attributes(@product).merge(id: params[:id]), user: current_user
        )
        render json: { data: { product: result[:model] } }
      end

      # Method that responds to the delete request and removes a product from the database
      def destroy
        Operations::ProductOperations::ApiDelete.call(params: params[:id], user: current_user)
        render body: nil, status: :no_content
      end

      private

      def product_params
        params.require(:product).permit(:name, :description, :price, :stock, :avatar, :term, :tag, :letter,
                                        :likes_count, :page)
      end

      def query_params
        params.slice(:term, :tag, :letter, :likes_count, :page)
      end

      def pundit_authorize
        authorize Product
      end

      def set_product
        @product = Products::ProductFinderService.call(params[:id])
      end

      def new_order_line
        @order_line = current_order.order_lines.new
      end
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# Define the Controllers required for the Product endpoints
class ProductsController < ApplicationController
  before_action :pundit_authorize, except: %i[index show]
  before_action :set_product, only: %i[edit update destroy]
  before_action :new_order_line, only: %i[index show]

  # Method that responds to the get request to list all the records
  # of products
  def index
    result = Operations::ProductOperations::Index.call(params: query_params)
    @products = result[:model]
  end

  # Method that responds to the get request to show an specific product
  def show
    result = Operations::ProductOperations::Show.call(params: params[:id])
    @product = result[:model]
  end

  # Method that allows the render of the new form for a new product
  def new
    @product = Product.new
  end

  # Method that respond to the create request to create a new product
  def create
    result = Operations::ProductOperations::Create.call(params: product_params)
    if result.success?
      redirect_to products_path
    else
      render :new
    end
  end

  # Method that allows the render of the edit form to change the product
  def edit; end

  # Method that responds to the update request to check if the user is an admin
  # and changes the stock and price params
  def update
    result = Operations::ProductOperations::Update.call(params: permitted_attributes(@product).merge(id: params[:id]),
                                                        user: current_user)
    if result.success?
      redirect_to products_path
    else
      render :edit
    end
  end

  # Method that responds to the delete request and removes a product from the database
  def destroy
    Operations::ProductOperations::Delete.call(params: params[:id], user: current_user)

    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :stock, :term, :tag, :letter, :likes_count)
  end

  def query_params
    params.slice(:term, :tag, :letter, :likes_count)
  end

  def pundit_authorize
    authorize Product
  end

  def set_product
    @product = Products::ProductFinderService.call(params[:id])
  end

  def new_order_line
    @order_line = current_order.order_lines.new
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

# Helpers for Product views
module ProductsHelper
end

app/views/products/_filter_bar.html.erb
<%= form_with model: @product, method: :get, html: {class: "flex justify-center items-center gap-6 py-2 border-2 border-slate-300"} do |form| %>
  <div>
    <%= form.label :term, "Search by:" %>
    <%= form.text_field :term %>
  </div>

  <div>
    <%= form.label :tag, "Sort by Tag:" %>
    <%= form.collection_select :tag, Tag.all, :id, :name, include_blank: true  %>
  </div>

  <div>
    <%= form.label :letter, "Sort by Name:" %>
    <%= form.radio_button :letter, "asc" %>
    <%= form.label :letter_asc, "ASC" %>
    <%= form.radio_button :letter, "desc" %>
    <%= form.label :letter_desc, "DESC" %>
  </div>

  <div>
    <%= form.label :likes_count, "Sort by Popularity:" %>
    <%= form.radio_button :likes_count, "asc" %>
    <%= form.label :likes_count_asc, "ASC" %>
    <%= form.radio_button :likes_count, "desc" %>
    <%= form.label :likes_count_desc, "DESC" %>
  </div>

  <div class="text-2xl">
    <%= form.submit "Sort", { class: button_style } %>
  </div>
<% end %>

app/views/products/_form.html.erb
<div class="flex flex-col gap-4 p-2 justify-center items-center">
  <%= form_with model: product, html: {class: "flex flex-col justify-center items-center gap-6 p-4 border-2 border-slate-300"} do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>

    <%= form.label :description %>
    <%= form.text_field :description %>

    <% if current_user&.admin? %>
      <%= form.label :price %>
      <%= form.number_field :price, required: true %>
    <% end %>

    <%= form.label :stock %>
    <%= form.number_field :stock, required: true %>
            
    <%= form.submit current_page?(new_product_path) ? "Add Product" : "Update", { class: button_style } %>
  <% end %>

  <%= link_to "Back", :back, { class: button_style } %>
</div>

app/views/products/_product_cart.html.erb
<div class="flex flex-col p-2 gap-2 text-lg border-2 border-slate-300 items-center">
  <p class="text-2xl"><%= product.name.capitalize %></p>
  <p class="text-xl">$ <%= number_with_precision(product.price, precision: 2) %></p>
  <p>Available: <%= product.stock %></p>

  <div class="flex gap-2">
  <p>Tags:</p>
  <% product.tags.each do |tag| %>
    <p><%= tag.name.capitalize %></p>
  <% end %>
  </div>

  <div class="flex gap-2">
    <% if policy(product.likes).create? %>
      
      <% if product.liked_by? current_user %>
        <%= button_to "Dislike?", like_path(product.find_like(current_user)), { method: :delete, class: button_style } %>
      <% else %>
        <%= button_to "Like?", product_likes_path(product), { method: :post, class: button_style } %>
      <% end %>
    <% end %>
    <p>Likes: <%= product.likes_count %></p>
  </div>

  <% if policy(product).update? %>
    <%= link_to "Edit product", edit_product_path(product), { class: button_style } %>
  <% end %>

  <% if policy(product).destroy? %>
    <%= button_to "Delete product", product_path(product), { method: :delete, class: button_style } %>
  <% end %>

  <div>
    <% if policy(@order_line).create? %>
      <%= form_with model: @order_line do |form| %>
        <%= form.hidden_field :product_id, value: product.id %>
          <div class="text-base">
            <%= form.label :quantity %>
          </div>
        <%= form.number_field :quantity, required: true %>
        <%= form.submit "Add to Cart", { class: button_style } %>
      <% end %>
    <% end %>
  </div>

  <% unless current_page?(product_path(product)) %>
  <%= link_to "See more...", product_path(product), { class: button_style } %>
  <% end %>
</div>

app/views/products/edit.html.erb
<div class="flex flex-col gap-4 p-2 justify-center items-center">
  <h2 class="text-3xl">Edit Product</h2>

  <%= render partial: "form", locals: { product: @product } %>
</div>

app/views/products/index.html.erb
<div class="flex flex-col justify-center">
  <%= render partial: "filter_bar" %>

  <div class="grid grid-cols-4 gap-2 p-2">
    <% if @products.empty? %>
      <p class="text-4xl text-red-500">No Records Found</p>
    <% else %>
      <% @products.each do |product| %>
        <%= render partial: "product_cart", locals: { product: product, order_line: @order_line }%>
      <% end %>
    <% end %>

    <% if policy(@products).create? %>
      <button class="flex flex-col p-2 gap-2 border-2 border-slate-300 justify-center items-center text-2xl">
        <%= link_to "New Product", new_product_path %>
      </button>
    <% end %>

    <% if current_user&.admin? %>
      <button class="flex flex-col p-2 gap-2 border-2 border-slate-300 justify-center items-center text-2xl">
        <%= link_to "See logs", logs_path %>
      </button>
    <% end %>

    <% if !current_user.nil? %>
      <button class="flex flex-col p-2 gap-2 border-2 border-slate-300 justify-center items-center text-2xl">
        <%= link_to "See Transactions", transactions_path %>
      </button>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="flex flex-col gap-4 p-2 justify-center items-center">
  <h2 class="text-3xl">Add new Product</h2>

  <%= render partial: "form", locals: { product: @product } %>
</div>

app/views/products/show.html.erb
<div class="flex flex-col gap-4 p-2 justify-center items-center">
  <%= render partial: "product_cart", locals: { product: @product, order_line: @order_line }%>

  <% if policy(Comment).create? %>
    <%= render partial: "comments/form", locals: { commentable: @product } %>
  <% end %>

  <%= render partial: "comments/comments", locals: { commentable: @product } %>

  <%= link_to "Back", :back, { class: button_style } %>
</div>