config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  use_doorkeeper
  root 'products#index'

  devise_for :users, controllers: { sessions: 'sessions' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  namespace :api do
    namespace :v1 do
      concern :commentable do
        resources :comments
      end

      resources :products do
        resources :likes, shallow: true, only: %i[create]
      end
      resources :order_lines
      resources :orders
      resources :users, concerns: :commentable
      resources :transactions, only: [:index]
      post '/authenticate', to: 'authentication#authenticate'
      post '/webhook', to: 'orders#webhook'
    end
  end

  concern :commentable do
    resources :comments
  end

  resources :products, concerns: :commentable do
    resources :likes, shallow: true, only: %i[create destroy]
  end
  resources :order_lines
  resources :orders, concerns: :commentable
  post 'checkout', to: 'orders#checkout'
  resources :logs, only: [:index]
  resources :transactions, only: [:index]
  get 'cart', to: 'orders#cart'

  resources :apidocs, only: [:index]
  get 'json', to: 'apidocs#json'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex flex-col gap-6">
    <header class="flex justify-around items-center p-3">
      <h1 class="text-7xl"><%= link_to "SNACK STORE", root_path %></h1>
      <ul class="flex flex-col gap-4">
        <% if user_signed_in? %>
          <li><p>Welcome <%= current_user.first_name %></p></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path, { class: button_style } %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, { method: :delete, class: button_style } %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path, { class: button_style } %></li>
          <li><p class="critics-navbar__message">Sign in to buy products</p></li>
        <% end %>
      </ul>
      <p>
        <% if current_page? cart_path%>
          <h2 class="text-3xl"><%= link_to "Back", :root, { class: button_style } %></h2>
        <% else %>
          <h2 class="text-3xl"><%= link_to "See Cart", cart_path, { class: button_style } %></h2>
        <% end %>
      </p>
      <p>
        <% if current_user %>
          <h2 class="text-3xl"><%= link_to "See Orders", orders_path, { class: button_style } %></h2>
        <% else %>
          <h2>Log in to see your orders</h2>
        <% end %>
      </p>
    </header>
    <main>
      <p class="text-4xl text-red-500"><%= flash[:warning] %></p>
      <p class="text-red-500"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>